//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHANUAudioVedioPlayListPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioTable
    {
        public int ID { get; set; }
        public byte[] Audio { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Name { get; set; }
    }
}
